survey/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)
import csv, random

author = 'Felix Sebastian Dossing'

doc = """
Your app description
"""


class Constants(BaseConstants):
    name_in_url = 'patsurvey'
    players_per_group = None
    num_rounds = 1

    points_per_box = 5

    number_of_surveys = 3

    with open('survey/disgust_questions.csv') as q:
        disgust = list(csv.DictReader(q))

    with open('survey/paternalism_questions.csv') as q:
        paternalism = list(csv.DictReader(q))

    with open('survey/personality.csv') as q:
        personality = list(csv.DictReader(q))

    with open('survey/ideology.csv') as q:
        ideology = list(csv.DictReader(q))

class Subsession(BaseSubsession):

    def creating_session(self):
        for p in self.get_players():
            p.bomb_placement = random.randint(0,100)


class Group(BaseGroup):
    pass


class Player(BasePlayer):

    disgust1 = models.CharField(help_text=Constants.disgust[0]['question'])
    disgust2 = models.CharField(help_text=Constants.disgust[1]['question'])
    disgust3 = models.CharField(help_text=Constants.disgust[2]['question'])
    disgust4 = models.CharField(help_text=Constants.disgust[3]['question'])
    disgust5 = models.CharField(help_text=Constants.disgust[4]['question'])
    disgust6 = models.CharField(help_text=Constants.disgust[5]['question'])
    disgust7 = models.CharField(help_text=Constants.disgust[6]['question'])
    disgust8 = models.CharField(help_text=Constants.disgust[7]['question'])
    disgust9 = models.CharField(help_text=Constants.disgust[8]['question'])
    disgust10 = models.CharField(help_text=Constants.disgust[9]['question'])
    disgust11 = models.CharField(help_text=Constants.disgust[10]['question'])
    disgust12 = models.CharField(help_text=Constants.disgust[11]['question'])
    disgust13 = models.CharField(help_text=Constants.disgust[12]['question'])
    disgust14 = models.CharField(help_text=Constants.disgust[13]['question'])

    disgust15 = models.CharField(help_text=Constants.disgust[14]['question'])
    disgust16 = models.CharField(help_text=Constants.disgust[15]['question'])
    disgust17 = models.CharField(help_text=Constants.disgust[16]['question'])
    disgust18 = models.CharField(help_text=Constants.disgust[17]['question'])
    disgust19 = models.CharField(help_text=Constants.disgust[18]['question'])
    disgust20 = models.CharField(help_text=Constants.disgust[19]['question'])
    disgust21 = models.CharField(help_text=Constants.disgust[20]['question'])
    disgust22 = models.CharField(help_text=Constants.disgust[21]['question'])
    disgust23 = models.CharField(help_text=Constants.disgust[22]['question'])
    disgust24 = models.CharField(help_text=Constants.disgust[23]['question'])
    disgust25 = models.CharField(help_text=Constants.disgust[24]['question'])
    disgust26 = models.CharField(help_text=Constants.disgust[25]['question'])
    disgust27 = models.CharField(help_text=Constants.disgust[26]['question'])

    boxes_opened = models.IntegerField()
    bomb_placement = models.IntegerField()

    def set_payoffs(self):
        if self.boxes_opened < self.bomb_placement:
            self.payoff = self.boxes_opened * Constants.points_per_box
        else:
            self.payoff = 0

    paternalism_question1 = models.CharField(help_text=Constants.paternalism[0]['question'])
    paternalism_question2 = models.CharField(help_text=Constants.paternalism[1]['question'])
    paternalism_question3 = models.CharField(help_text=Constants.paternalism[2]['question'])
    paternalism_question4 = models.CharField(help_text=Constants.paternalism[3]['question'])
    paternalism_question5 = models.CharField(help_text=Constants.paternalism[4]['question'])
    paternalism_question6 = models.CharField(help_text=Constants.paternalism[5]['question'])
    paternalism_question7 = models.CharField(help_text=Constants.paternalism[6]['question'])
    paternalism_question8 = models.CharField(help_text=Constants.paternalism[7]['question'])
    paternalism_question9 = models.CharField(help_text=Constants.paternalism[8]['question'])

    paternalism_question10 = models.CharField(widget=widgets.RadioSelect())

    personality1 = models.CharField(help_text=Constants.personality[0]['question'])
    personality2 = models.CharField(help_text=Constants.personality[1]['question'])
    personality3 = models.CharField(help_text=Constants.personality[2]['question'])
    personality4 = models.CharField(help_text=Constants.personality[3]['question'])
    personality5 = models.CharField(help_text=Constants.personality[4]['question'])
    personality6 = models.CharField(help_text=Constants.personality[5]['question'])
    personality7 = models.CharField(help_text=Constants.personality[6]['question'])
    personality8 = models.CharField(help_text=Constants.personality[7]['question'])
    personality9 = models.CharField(help_text=Constants.personality[8]['question'])
    personality10 = models.CharField(help_text=Constants.personality[9]['question'])

    pol_scale_pos = models.CharField(verbose_name=Constants.ideology[0]['introduction'],
                                     widget=widgets.RadioSelect())
    income_equity = models.CharField(verbose_name=Constants.ideology[1]['introduction'],
                                     widget=widgets.RadioSelect())
    private_vs_state = models.CharField(verbose_name=Constants.ideology[2]['introduction'],
                                     widget=widgets.RadioSelect())
    government_responsibility = models.CharField(verbose_name=Constants.ideology[3]['introduction'],
                                     widget=widgets.RadioSelect())
    competition = models.CharField(verbose_name=Constants.ideology[4]['introduction'],
                                     widget=widgets.RadioSelect())
    hard_work = models.CharField(verbose_name=Constants.ideology[5]['introduction'],
                                     widget=widgets.RadioSelect())
    wealth = models.CharField(verbose_name=Constants.ideology[6]['introduction'],
                                     widget=widgets.RadioSelect())

    vote2015 = models.CharField(widget=widgets.RadioSelect())
    votenow = models.CharField(widget=widgets.RadioSelect())

    gender = models.CharField(widget=widgets.RadioSelect())
    height = models.IntegerField(min=0, max=300)
    weight = models.IntegerField(min=0, max=300)
    birthyear = models.CharField()
    smoker = models.CharField(widget=widgets.RadioSelect())
    zipcode = models.IntegerField(min=0, max=9999)

survey/views.py
from otree.api import Currency as c, currency_range
from . import models
from ._builtin import Page, WaitPage
from .models import Constants



class Risk_instructions(Page):
    pass

class Risk_main(Page):
    form_model = models.Player
    form_fields = ['boxes_opened']

    def before_next_page(self):
        self.player.set_payoffs()

class Risk_results(Page):
    pass

class Disgust_survey1(Page):
    form_model = models.Player
    form_fields = ['disgust{}'.format(i) for i in range(1,15)]

class Disgust_survey2(Page):
    form_model = models.Player
    form_fields = ['disgust{}'.format(i) for i in range(15,28)]

class Paternalism_questions1(Page):
    form_model = models.Player
    form_fields = ['paternalism_question{}'.format(i) for i in range(1,6)]

class Paternalism_questions2(Page):
    form_model = models.Player
    form_fields = ['paternalism_question{}'.format(i) for i in range(6,8)]

class Paternalism_questions3(Page):
    form_model = models.Player
    form_fields = ['paternalism_question{}'.format(i) for i in range(8,10)]

class Paternalism_questions4(Page):
    form_model = models.Player
    form_fields = ['paternalism_question10']

    def paternalism_question10_choices(self):
        return [
            "We should keep the current system, which requires people to sign up if they want to be an organ donor",
            "We should implement a new system, where those who don't want to be an organ donor should resign",
            "Everyone should be an organ donor without the possibility to resign"
        ]
class Ideology(Page):
    form_model = models.Player
    form_fields = ['pol_scale_pos', 'income_equity', 'private_vs_state', 'government_responsibility',
                   'competition', 'hard_work', 'wealth']

    def pol_scale_pos_choices(self):
        scale = ['{}'.format(i) for i in range(2,10)]
        scale.insert(0,Constants.ideology[0]['1'])
        scale.append(Constants.ideology[0]['10'])
        return scale

    def income_equity_choices(self):
        scale = ['{}'.format(i) for i in range(2,10)]
        scale.insert(0,Constants.ideology[1]['1'])
        scale.append(Constants.ideology[1]['10'])
        return scale

    def private_vs_state_choices(self):
        scale = ['{}'.format(i) for i in range(2,10)]
        scale.insert(0,Constants.ideology[2]['1'])
        scale.append(Constants.ideology[2]['10'])
        return scale

    def government_responsibility_choices(self):
        scale = ['{}'.format(i) for i in range(2,10)]
        scale.insert(0,Constants.ideology[3]['1'])
        scale.append(Constants.ideology[3]['10'])
        return scale

    def competition_choices(self):
        scale = ['{}'.format(i) for i in range(2,10)]
        scale.insert(0,Constants.ideology[4]['1'])
        scale.append(Constants.ideology[4]['10'])
        return scale

    def hard_work_choices(self):
        scale = ['{}'.format(i) for i in range(2,10)]
        scale.insert(0,Constants.ideology[5]['1'])
        scale.append(Constants.ideology[5]['10'])
        return scale

    def wealth_choices(self):
        scale = ['{}'.format(i) for i in range(2,10)]
        scale.insert(0,Constants.ideology[6]['1'])
        scale.append(Constants.ideology[6]['10'])
        return scale

    #Højre Venstre
    #Kan markedet allokere ressourcer effektivt
    #33 helping the poor
    #34 work vs luck

class Voting(Page):
    form_model = models.Player
    form_fields = ['vote2015', 'votenow']

    def vote2015_choices(self):
        return [
            "Socialdemokratiet (A)",
            "Radikale Venstre (B)",
            "Det Konservative Folkeparti (C)",
            "SF - Socialistisk Folkeparti (F)",
            "Liberal Alliance (I)",
            "Kristendemokraterne (K)",
            "Dansk Folkeparti (O)",
            "Venstre - Danmarks liberale parti (V)",
            "Enhedslisten - De Rød-Grønne (Ø)",
            "Alternativet (Å)",
            "I chose not to vote",
            "I am not allowed to vote in the Danish general election"
        ]

    def votenow_choices(self):
        return [
            "Socialdemokratiet (A)",
            "Radikale Venstre (B)",
            "Det Konservative Folkeparti (C)",
            "SF - Socialistisk Folkeparti (F)",
            "Liberal Alliance (I)",
            "Kristendemokraterne (K)",
            "Dansk Folkeparti (O)",
            "Venstre - Danmarks liberale parti (V)",
            "Enhedslisten - De Rød-Grønne (Ø)",
            "Alternativet (Å)",
            "I chose not to vote",
            "I am not allowed to vote in the Danish general election"
        ]

class Personality(Page):
    form_model = models.Player
    form_fields = ['personality{}'.format(i) for i in range(1,11)]


class Demographics(Page):
    form_model = models.Player
    form_fields = ['gender','height','weight','birthyear','smoker']

    def gender_choices(self):
        return [
            "Female",
            "Male",
            "Other"
        ]
    def birthyear_choices(self):
        return ["{}".format(i) for i in range(1900,2010)]
    def smoker_choices(self):
        return [
            "are a smoker",
            "are a smoker, but have tried to quit",
            "have been a smoker, but have quit",
            "have never been a smoker"
        ]


    #36 - difficulty handling money, impulsivity and so on



#To be in survey: CR-test, "type-questions"
# Social dominance orientation
# Political orientation Two-dimensional


class Results(Page):
    pass

page_sequence = [
    Risk_main,
    Risk_results,
    Disgust_survey1,
    Disgust_survey2,
    Paternalism_questions1,
    Paternalism_questions2,
    Paternalism_questions3,
    Paternalism_questions4,
    Ideology,
    Personality,
    Voting,
    Demographics
]

survey/templates/survey/Demographics.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Survey
{% endblock %}

{% block content %}

{% formfield player.smoker with label="A smoker is a person who smokes every day. Please select the answer which describes you best. You..." %}
{% formfield player.gender with label="What is your gender?" %}
{% formfield player.height with label="How tall are you in cm without your shoes on?" %}
{% formfield player.weight with label="How much do you weigh in kg?" %}
{% formfield player.birthyear with label="Which year where you born?" %}

{% next_button %}

{% endblock %}

survey/templates/survey/Disgust_survey1.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Survey
{% endblock %}

{% block content %}

<div id="instructions_div" class="instructions well well-1g">
<p>
  Please indicate how much you agree with each of the following statements,
  or how true it is about you.<br>
  Please choose a number (0-4) to indicate your answer:<br><br>
  0 = Strongly disagree (very untrue about me)<br>
  1 = Mildly disagree (somewhat untrue about me)<br>
  2 = Neither agree nor disagree<br>
  3 = Mildly agree (somewhat true about me)<br>
  4 = Strongly agree (very true about me)<br>
</p>
</div>

<table class="table">
  <tr>
    <th>Question</th><th>0</th><th>1</th><th>2</th><th>3</th><th>4</th>
  </tr>
  {% for field in form %}
  <tr>
    <td width="50%">
      {{ field.help_text }}
      {{ field.errors }}
    </td>
    <td><input type="radio" name="{{ field.html_name }}" value="0" required {% if field.value|stringformat:"s" == '0' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="1" required {% if field.value|stringformat:"s" == '1' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="2" required {% if field.value|stringformat:"s" == '2' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="3" required {% if field.value|stringformat:"s" == '3' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="4" required {% if field.value|stringformat:"s" == '4' %}checked{% endif %}></td>

  </tr>
  {% endfor %}
<table class="table">

    {% next_button %}

{% endblock %}

survey/templates/survey/Disgust_survey2.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Survey
{% endblock %}

{% block content %}

<div id="instructions_div" class="instructions well well-1g">
<p>
  How disgusting would you find each of the following experiences?<br>
  Please choose a number (0-4) to indicate your answer:<br><br>
  0 = Not disgusting at all<br>
  1 = Slightly disgusting<br>
  2 = Moderately disgusting<br>
  3 = Very disgusting<br>
  4 = Extremely disgusting
</p>
</div>

<table class="table">
  <tr>
    <th>Question</th><th>0</th><th>1</th><th>2</th><th>3</th><th>4</th>
  </tr>
  {% for field in form %}
  <tr>
    <td width="50%">
      {{ field.help_text }}
      {{ field.errors }}
    </td>
    <td><input type="radio" name="{{ field.html_name }}" value="0" required {% if field.value|stringformat:"s" == '0' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="1" required {% if field.value|stringformat:"s" == '1' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="2" required {% if field.value|stringformat:"s" == '2' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="3" required {% if field.value|stringformat:"s" == '3' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="4" required {% if field.value|stringformat:"s" == '4' %}checked{% endif %}></td>

  </tr>
  {% endfor %}
<table class="table">



    {% next_button %}

{% endblock %}

survey/templates/survey/Ideology.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Survey
{% endblock %}

{% block content %}

<!-- <table class="table">

</table>


<table class="table">
  <tr>
    <th>0</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th>
  </tr>
  {% for field in form %}
  <tr>
    <td><input type="radio" name="{{ field.html_name }}" value="0" required {% if field.value|stringformat:"s" == '0' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="1" required {% if field.value|stringformat:"s" == '1' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="2" required {% if field.value|stringformat:"s" == '2' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="3" required {% if field.value|stringformat:"s" == '3' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="4" required {% if field.value|stringformat:"s" == '4' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="5" required {% if field.value|stringformat:"s" == '5' %}checked{% endif %}></td>
  </tr>
  {% endfor %}
<table class="table"> -->

{% for field in form %}
{% formfield field %}
{% endfor %}

{% next_button %}

{% endblock %}

{% block styles %}
<style>

.form-group {
  padding-top: 30px;
}

</style>
{% endblock %}

survey/templates/survey/Paternalism_questions1.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Survey
{% endblock %}

{% block content %}

<div id="instructions_div" class="instructions well well-1g">
<p>
  Please indicate how much you agree with each of the following statements.<br>
  Please choose a number (0-4) to indicate your answer:<br><br>
  0 = Strongly disagree (very untrue about me)<br>
  1 = Mildly disagree (somewhat untrue about me)<br>
  2 = Neither agree nor disagree<br>
  3 = Mildly agree (somewhat true about me)<br>
  4 = Strongly agree (very true about me)<br>
  5 = Don't know<br>
</p>
</div>

<p>
  In recent years, it has been discussed to what extent the state should control people's behavior.
  Do you agree or disagree that the state should legislate to affect...
</p>

<table class="table">
  <tr>
    <th>Question</th><th>0</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th>
  </tr>
  {% for field in form %}
  <tr>
    <td width="50%">
      {{ field.help_text }}
      {{ field.errors }}
    </td>
    <td><input type="radio" name="{{ field.html_name }}" value="0" required {% if field.value|stringformat:"s" == '0' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="1" required {% if field.value|stringformat:"s" == '1' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="2" required {% if field.value|stringformat:"s" == '2' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="3" required {% if field.value|stringformat:"s" == '3' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="4" required {% if field.value|stringformat:"s" == '4' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="5" required {% if field.value|stringformat:"s" == '5' %}checked{% endif %}></td>
  </tr>
  {% endfor %}
<table class="table">

    {% next_button %}

{% endblock %}

survey/templates/survey/Paternalism_questions2.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Survey
{% endblock %}

{% block content %}

<div id="instructions_div" class="instructions well well-1g">
<p>
  Please indicate whether you agree with each of the following statements.<br>
</p>
</div>
<table class="table">
  <tr>
    <th>Question</th><th>Yes</th><th>No</th><th>Don't know</th>
  </tr>
  {% for field in form %}
  <tr>
    <td width="70%">
      {{ field.help_text }}
      {{ field.errors }}
    </td>
    <td><input type="radio" name="{{ field.html_name }}" value="0" required {% if field.value|stringformat:"s" == '0' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="1" required {% if field.value|stringformat:"s" == '1' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="2" required {% if field.value|stringformat:"s" == '2' %}checked{% endif %}></td>
  </tr>
  {% endfor %}
<table class="table">

    {% next_button %}

{% endblock %}

survey/templates/survey/Paternalism_questions3.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Survey
{% endblock %}

{% block content %}

<div id="instructions_div" class="instructions well well-1g">

<p>
  Please indicate how much you agree with each of the following statements.<br>
  Please choose a number (0-4) to indicate your answer:<br><br>
  0 = Strongly disagree (very untrue about me)<br>
  1 = Mildly disagree (somewhat untrue about me)<br>
  2 = Neither agree nor disagree<br>
  3 = Mildly agree (somewhat true about me)<br>
  4 = Strongly agree (very true about me)<br>
  5 = Don't know<br>
</p>
</div>
<p>
  In recent years, it has been discussed to what extent the state should try to affect people's
  behavior by using psychologists' knowledge about how we make decisions.
</p>

<table class="table">
  <tr>
    <th>Question</th><th>0</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th>
  </tr>
  {% for field in form %}
  <tr>
    <td width="50%">
      {{ field.help_text }}
      {{ field.errors }}
    </td>
    <td><input type="radio" name="{{ field.html_name }}" value="0" required {% if field.value|stringformat:"s" == '0' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="1" required {% if field.value|stringformat:"s" == '1' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="2" required {% if field.value|stringformat:"s" == '2' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="3" required {% if field.value|stringformat:"s" == '3' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="4" required {% if field.value|stringformat:"s" == '4' %}checked{% endif %}></td>
    <td><input type="radio" name="{{ field.html_name }}" value="5" required {% if field.value|stringformat:"s" == '5' %}checked{% endif %}></td>
  </tr>
  {% endfor %}
<table class="table">

    {% next_button %}

{% endblock %}

survey/templates/survey/Paternalism_questions4.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Survey
{% endblock %}

{% block content %}
<div id="instructions_div" class="instructions well well-1g">
<p>
  Please indicate which of the following statements you agree with.<br>
</p>
</div>
<p>
  There is a need for organ donors. Many people say that they would like to be an organ donor, but
  that they just don't sign up. It has therefore been suggested that everyone automatically is
  registered as an organ donor and has to resign if they don't want to. Do you think that...
</p>

{% formfield player.paternalism_question10 with label="" %}

{% next_button %}

{% endblock %}

survey/templates/survey/Risk_instructions.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Bomber task instructions
{% endblock %}

{% block content %}

<div id="instructions_div" class="instructions well well-1g">
<p>
  You will now participate in the "bomber task". On the following screen you will see 100 boxes. You may highligt as many boxes as you want in order to open them. For each box you open, you earn {{ Constants.points_per_box }} points.
  There is a bomb in one of the boxes. The bomb is placed at random, which means that it may be inside any box with an equal probability. If the bomb is inside one of the boxes you open, then you will get 0 points. Points have the
  same value as in the previous experiments.
</p>
</div>
    {% next_button %}

{% endblock %}

survey/templates/survey/Risk_main.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Survey
{% endblock %}

{% block content %}

<div id="instructions_div" class="instructions well well-1g">
<p>
  On this screen screen you see 100 boxes. You may highligt as many boxes as you want in order to open them. For each box you open, you earn {{ Constants.points_per_box }} points.
  There is a bomb in one of the boxes. The bomb is placed at random, which means that it may be inside any box with an equal probability. If the bomb is inside one of the boxes you open, then you will get 0 points.
</p>
</div>

<p>
  Please choose the amount of boxes you wish to open by clicking below.<br><br>
</p>
<p>
  You have selected <span id="chosen" class="number">0</span> out of <span class="number">100</span> boxes.
</p>

<div id="bomber_box">
</div>

<p id="click-info" class="text-center"></p>

<input type="hidden" name="boxes_opened" value="0" id="id_boxes_opened"/>

    {% next_button %}

{% block styles %}

<style type="text/css">

  #bomber_box {
    margin-left: 25%;
    width: 50%;
  }
  .box {
    background-color:  lightgrey;
    width: 10%;
    height: 10%;
    float: left;
    border-style: solid;
    border-width: thin;
    border-color: black;
  }
  .number {
    font-size: 30px;
  }

</style>

{% endblock %}

{% block script %}
<script>

$('#bomber_box').css('height', $('#bomber_box').css('width'));

for (i=0; i < 100; i++) {
  $('#bomber_box').append('<div class="box" id="box'+i+'"></div>');
}

mouseover_box = 999;
mouseover_main = false;
selected_box = 999; // 999 when no box is selected
mouseover_button = false;

// CHECK IF MOUSE IS OVER BUTTON
$('.next-button').mouseenter(function(event) {
  mouseover_button = true;
})
$('.next-button').mouseleave(function(event) {
  mouseover_button = false;
})

// CHECK IF MOUSE IS OVER MAIN BOX
$(document).ready(function() {
  $('#bomber_box').mouseover(function() {
    mouseover_main = true;
  });
  $('#bomber_box').mouseout(function() {
    mouseover_main = false;
  })
})

// SET MOUSE OVER BOX
$(window).mousemove(function(event) {
  if (mouseover_main == true) {
    for (i = 0; i < 100; i++) {
      $('#box'+i).hover(function() {
        mouseover_box = this.id.replace('box', '');
      })
    }
  }
  else {
    mouseover_box = 999;
  }
})

// SET SELECTED BOX
$(window).click(function(event) {
  if (mouseover_button == false) {
    selected_box = mouseover_box
  }
})

// COLOR MOUSE OVER
$(window).mousemove(function(event) {
  if (mouseover_main == true) {
    for (i = 0; i < 100; i++) {
      $('#box'+i).css('background-color', 'lightgrey');
    }
    for (i = 0; i <= mouseover_box; i++) {
      $('#box'+i).css('background-color', 'grey');
    }
  }
  else {
    for (i = 0; i < 100; i++) {
      $('#box'+i).css('background-color', 'lightgrey');
    }
  }
})

$(window).mousemove(function(event) {
  if (selected_box != 999) {
    for (i = 0; i <= selected_box; i++) {
      $('#box'+i).css('background-color', 'grey');
    }
    $('#chosen').html(parseInt(selected_box)+1);
    $('#click-info').html('Click outside the box to unselect');
    $('#id_boxes_opened').val(parseInt(selected_box)+1);
  }
  else {
    $('#chosen').html('0')
    $('#click-info').html('')
    $('#id_boxes_opened').val(0)
  }
})

</script>
{% endblock %}

{% endblock %}

survey/templates/survey/Risk_results.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Bomber task results
{% endblock %}

{% block content %}

<p>You chose to open {{ player.boxes_opened }} boxes. The bomb was under box number {{ player.bomb_placement }}. You earned {{ player.payoff }}.

    {% next_button %}
{% endblock %}